version: '3'

services:
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    build:
      context: .
      dockerfile: sql.Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'YES'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: kyoto
    ports:
      - "3306:3306"
